### ISSUE TITLE
Reset password

### ISSUE THREAD

**Issue by squeaky1273** [UPstartDeveloper/explorer_buddy#5]
The reset password with the email does not really work.

**Comment by UPstartDeveloper** [comment]
Hey @squeaky1273,  thanks for pointing this out.

It looks like I just forgot to export the environment variables regarding this feature (i.e `*'EMAIL...'` in `explorer/settings,py`) over to the Heroku version as config variables.

The command used to resolve this from `Terminal.app was heroku config: set VAR_NAME=VALUE`.
